# Generated by Django 4.2.5 on 2023-10-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sex',
            new_name='gender',
        ),
    ]
