# Generated by Django 4.2.5 on 2023-11-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birth_date',
            new_name='date_of_birth',
        ),
    ]
