# Generated by Django 4.2.5 on 2023-11-02 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_birth_date_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
