# Generated by Django 4.2.5 on 2023-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_address_line1_profile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
