# Generated by Django 4.2.5 on 2023-11-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postcode',
            new_name='postalcode',
        ),
    ]
