# Generated by Django 4.2.5 on 2023-11-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_postalcode_profile_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
