# Generated by Django 4.2.5 on 2023-11-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_profession_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
